<template>
  <div class="">
    <div class="pt-24">
      <div class="container px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center w-full">
        <!--Left Col-->
        <div class="flex flex-col w-full md:w-2/5 justify-center items-start text-center md:text-left">
          <h1 class="my-4 text-5xl font-bold leading-tight">
            Cap
          </h1>
          <p class="leading-normal text-2xl mb-8 font-thin">
            Crypto Market Capitalization Index
          </p>

          <a class="mx-auto lg:mx-0 hover:underline bg-white text-gray-800 font-bold rounded-full my-6 py-4 px-8 shadow-lg flex items-center">
            Sale soon!
          </a>
        </div>
        <!--Right Col-->
        <div class="w-full md:w-3/5 py-6 text-center flex justify-center">
          <Cap />
        </div>
      </div>
    </div>
    <section class="bg-gray-100 text-gray-900 py-16">
      <h2 class="text-3xl text-center mb-8">Crypto Market</h2>
      <div class="container mx-auto flex flex-wrap">
        <p class="w-full md:flex-1 p-8"></p>
        <p class="w-full md:flex-1 p-8">Cap Protocol is a decentralized elastic supply protocol for creating indices of other tokens. It maintains a price peg by adjusting supply directly to and from wallet holders based on data feed generated by off-chain oracles.</p>
        <p class="w-full md:flex-1 p-8">By investing into the Cap Token, you speculate into the hole crypto market. So there is no need to risk-invest in single projects anymore.</p>
        <p class="w-full md:flex-1 p-8"></p>
      </div>
    </section>
    <!-- <section class="bg-gray-200 text-gray-900 py-16">
      <h2 class="text-3xl text-center mb-8">Assets</h2>
      <div class="container mx-auto flex flex-wrap justify-around items-start">

      </div>
    </section> -->
  </div>
</template>

<script>
import Cap from '@/assets/logos/cap.svg'

export default {
  components: {
    Cap
  }
}
</script>

<style lang="css" scoped>
</style>
